### Login to get JWT token
POST http://localhost:8081/login
Content-Type: application/json

{
  "username": "Vignesh",
  "password": "vignesh123"
}

### Get Data from db
GET http://localhost:8081/46f5b866-bbcd-4b57-b82e-f27c54dc0feb
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNzM3NTU3Nzg0fQ.eMjrIoLwWWx6GqP5RFDcW_H25nNr2mZ2vf4ddRGGsGo

### GET ALL USERS DATA
GET http://localhost:8081/
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNzM3NTU3Nzg0fQ.eMjrIoLwWWx6GqP5RFDcW_H25nNr2mZ2vf4ddRGGsGo

### ADD USER IN DATABASES
POST http://localhost:8081/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNzM3NTU3Nzg0fQ.eMjrIoLwWWx6GqP5RFDcW_H25nNr2mZ2vf4ddRGGsGo

{
  "username": "AchammagariPoojitha",
  "password": "poojitha123"
}


### ADD USER DETAILS
POST http://localhost:8081/add/details
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNzM3NTU3Nzg0fQ.eMjrIoLwWWx6GqP5RFDcW_H25nNr2mZ2vf4ddRGGsGo

{
  "email": "poojitha@gmail.com",
  "phone": "857496852",
  "company": "Amozan",
  "name": "Poojitha"
}


### Update the User
POST http://localhost:8081/update/4347887b-5764-4ea8-9451-d5304760dbd9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNzM3NTU3Nzg0fQ.eMjrIoLwWWx6GqP5RFDcW_H25nNr2mZ2vf4ddRGGsGo


### Delete user data 
DELETE http://localhost:8081/delete/092008d4-78a9-414e-b1d4-9335b33d79d9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNzM3NTU3Nzg0fQ.eMjrIoLwWWx6GqP5RFDcW_H25nNr2mZ2vf4ddRGGsGo