### Login to get JWT token
POST http://localhost:8081/login
Content-Type: application/json

{
  "username": "VigneshMadam",
  "password": "vignesh123"
}

### Get single user Data from db
GET http://localhost:8081/user
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJ1c2VybmFtZSI6IlZpZ25lc2hNYWRhbSIsImlhdCI6MTczNzY0MjEwNn0.BGt05w5UTBS5JLRGAOJGnmfe1xwtmNvEi5RSDhiFGxw

### GET ALL USER DATA
GET http://localhost:8081/alldata
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJ1c2VybmFtZSI6IlZpZ25lc2hNYWRhbSIsImlhdCI6MTczNzY0MjEwNn0.BGt05w5UTBS5JLRGAOJGnmfe1xwtmNvEi5RSDhiFGxw


### Get Data from db
GET http://localhost:8081/
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJ1c2VybmFtZSI6IlZpZ25lc2hNYWRhbSIsImlhdCI6MTczNzY0MjEwNn0.BGt05w5UTBS5JLRGAOJGnmfe1xwtmNvEi5RSDhiFGxw

{
  "search": "poo",
  "company": ""
}

### GET ALL USERS DATA
GET http://localhost:8081/
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJ1c2VybmFtZSI6IlZpZ25lc2hNYWRhbSIsImlhdCI6MTczNzY0MjEwNn0.BGt05w5UTBS5JLRGAOJGnmfe1xwtmNvEi5RSDhiFGxw

### ADD USER IN DATABASES
POST http://localhost:8081/add
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJ1c2VybmFtZSI6IlZpZ25lc2hNYWRhbSIsImlhdCI6MTczNzY0MjEwNn0.BGt05w5UTBS5JLRGAOJGnmfe1xwtmNvEi5RSDhiFGxw

{
  "username": "NickRoa",
  "password": "nickroa123",
  "premium": false
}


### ADD USER DETAILS
POST http://localhost:8081/addcustomer
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJ1c2VybmFtZSI6IlZpZ25lc2hNYWRhbSIsImlhdCI6MTczNzY0MjEwNn0.BGt05w5UTBS5JLRGAOJGnmfe1xwtmNvEi5RSDhiFGxw

{
  "email": "ravikumar@gmail.com",
  "phone": "8235679135",
  "company": "Google",
  "name": "ravi"
}


### Update the User
POST http://localhost:8081/update/24
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJ1c2VybmFtZSI6IlZpZ25lc2hNYWRhbSIsImlhdCI6MTczNzY0MjEwNn0.BGt05w5UTBS5JLRGAOJGnmfe1xwtmNvEi5RSDhiFGxw


### Delete customer data 
DELETE http://localhost:8081/deletecustomer/
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJ1c2VybmFtZSI6IlZpZ25lc2hNYWRhbSIsImlhdCI6MTczNzY0MjEwNn0.BGt05w5UTBS5JLRGAOJGnmfe1xwtmNvEi5RSDhiFGxw


### Delete user data
DELETE http://localhost:8081/deleteuser/10
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJ1c2VybmFtZSI6IlZpZ25lc2hNYWRhbSIsImlhdCI6MTczNzY0MjEwNn0.BGt05w5UTBS5JLRGAOJGnmfe1xwtmNvEi5RSDhiFGxw